version: 0.0
os: linux
files: 
  - source: /
    destination: /var/www/html
hooks: 
   BeforeInstall:
    - location: scripts/noop.sh
      timeout: 10
      runas: root
   AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 30
      runas: root